/**
 * Guião de narração / leitura enriquecida — Português de Portugal (pt-PT).
 * Fonte única (§8.1): alimenta TTS e painel «Aa». Chave = número do slide (1..26).
 * Localização PT (§8.5): €, ortografia e léxico de Portugal (ecrã, telemóvel, gestão).
 */
export const NARRATION: Record<number, string> = {
  1: 'O Discovery Health é a Discovery especializada em saúde. A Aura, médica virtual, ouve o doente, estrutura os sintomas, pede auto-exames orientados e prepara um laudo acionável. Em paralelo, a operação da clínica organiza agenda, cobrança, stock, fatura e prevenção de fraude. Sete módulos, um único percurso do doente.',
  2: 'Antes de começar, o doente aceita três documentos. Termos de utilização, política de privacidade e — o mais sensível — o consentimento de biometria de voz, exigido pelo RGPD. O aceite é explícito, documento a documento; nada de letra miudinha escondida.',
  3: 'A identificação cruza o número de identificação fiscal com registos públicos e a morada com o código postal. Os campos chegam pré-preenchidos, mas o doente confere e ajusta. Dado público poupa digitação; a conferência mantém o controlo com a pessoa.',
  4: 'Antes de libertar qualquer dado, o sistema pergunta: encontrei alguém com este registo, é o senhor? O nome aparece mascarado e só passa a texto aberto depois de um gesto explícito do doente. Confirmação de identidade sem expor dados antes de tempo.',
  5: 'A Aura apresenta-se com voz calorosa, nada robótica. Explica que vai ouvir com calma, organizar o relato e destacar o que merece atenção médica mais rápida. O texto surge sincronizado com a fala — o doente lê e ouve ao mesmo tempo.',
  6: 'Agora o doente fala à vontade até dois minutos, sem perguntas pelo meio. A forma de onda reage à voz em tempo real. Falar à sua maneira, sem termo técnico, capta a nuance que um formulário perderia.',
  7: 'A Aura já ouviu. Devolve o que entendeu — cefaleia pulsátil há três dias, pior à tarde, sensível à luz — e faz uma pergunta adaptativa, no tom da Comunicação Não-Violenta. Em paralelo, extrai sinais: dor seis em dez, fotossensibilidade, ecrã como gatilho provável.',
  8: 'Os sinais fisiológicos entram classificados: índice de massa corporal, tensão arterial, frequência cardíaca, glicemia. Cada valor recebe um rótulo clínico e os sinais de alarme acendem. Tensão 128 por 82 passa logo a pré-hipertensão — sem o doente ter de interpretar números.',
  9: 'A biblioteca de auto-exames traz guias visuais passo a passo: mama, próstata, pele, língua, pulso. O doente marca o que quer fazer e segue a orientação. No exame da pele, o ABCDE do melanoma guia a captura da lesão.',
  10: 'Trouxe exames? O doente carrega PDF, JPG ou PNG até vinte megabytes cada. O IconsAI Vision lê cada ficheiro em segundo plano — hemograma, colesterol, ressonância — e usa o resultado para montar o laudo. Sem digitação manual.',
  11: 'Com base no áudio, a IA cruza o relato com o catálogo de medicação por recuperação aumentada. Sugere o que combina com o que foi contado; o doente confirma dose e frequência. A medicação entra com posologia preenchida.',
  12: 'O chat conduz a entrevista estruturada, citando trechos literais do áudio para mostrar que ouviu. As perguntas fecham intensidade, impacto no sono e gatilhos. Cada resposta torna-se um dado no painel lateral.',
  13: 'O laudo sai no formato SOAP — subjetivo, objetivo, avaliação e plano — com ligação pública e selo de proteção de dados em saúde. Ao lado, a gestão clínica organiza-se: agenda, stock com reposição automática e resumo do doente em áudio.',
  14: 'A agenda da semana mostra os turnos. Arrastar o doente para um horário dispara confirmação automática por WhatsApp, com lembrete vinte e quatro horas antes. Sem telefonema, sem retrabalho.',
  15: 'A faturação cruza a curva real com a agenda confirmada, semana a semana. Bilhete médio de cinquenta e dois euros, cancelamentos em oito vírgula quatro por cento, realizado em noventa e seis por cento do previsto. A diferença aparece antes de fechar o mês.',
  16: 'O armazém mostra stock atual, mínimo e sugestão de compra calculada pelo consumo médio das últimas quatro semanas. Vermelho é abaixo do mínimo. Três artigos já estão encomendados pela reposição automática.',
  17: 'A farmácia controla medicamentos por lote, validade e classe, com rastreabilidade completa para o INFARMED. Os alertas acendem sessenta dias antes da validade — dois lotes a expirar em menos de noventa dias.',
  18: 'A cobrança é automatizada por WhatsApp Business com referência Multibanco e MB WAY. Sequência humanizada: lembrete três dias antes, um dia antes e no próprio dia. O doente paga em segundos e o recibo e a fatura saem automáticos.',
  19: 'Chegou um recibo e a IA forense valida-o. Compara metadados, origem, pixéis e cruza com transações reais. Pontuação de confiança trinta e oito em cem: a data foi reescrita sobre o PDF e o valor é quatro vezes a tabela. Reembolso bloqueado, revisão humana em menos de um minuto.',
  20: 'Depois de cada consulta, a fatura eletrónica é emitida automaticamente e comunicada à Autoridade Tributária, com devolução de XML e PDF. Catorze emitidas hoje, uma a aguardar resposta, comunicação ao e-Fatura em direto.',
  21: 'A previsão de receita projeta doze meses com um modelo VAR, sazonalidade e feriados. Crescimento anual composto de dezoito vírgula quatro por cento, pico entre março e maio, projeção de seiscentos e quarenta mil euros. A banda sombreada é o intervalo de confiança de oitenta por cento.',
  22: 'O diagnóstico assistido vai de sintomas para CID-10 com probabilidade calibrada e daí para um plano de ação. Cefaleia de tensão com setenta e dois por cento, enxaqueca com dezanove. A decisão clínica final é sempre do médico; a IA é apoio.',
  23: 'A pontuação de risco populacional combina comorbilidades, idade e adesão para apontar quem está em risco de perda. Três doentes entram em busca ativa hoje. Esperança de vida ajustada de setenta e oito vírgula quatro anos, intervalo de confiança de noventa e cinco por cento.',
  24: 'A navegação do doente desenha a trajetória prevista com um modelo de Markov. Cada nó é uma etapa do tratamento; cada ligação, a probabilidade de transição. Percurso conservador, sessenta e sete por cento de recuperação por seiscentos e oitenta euros; intensivo, oitenta e nove por cento por mil novecentos e quarenta.',
  25: 'A matriz de evidência cruza combinações de tratamento com desfechos, cada célula com probabilidade e intervalo de confiança de noventa e cinco por cento de fontes médicas. A monoterapia A traz sessenta e dois por cento de remissão; A mais B sobe para setenta e oito; A mais B mais C chega a oitenta e quatro.',
  26: 'Obrigado pela atenção. Discovery Health, uma criação icons ai.',
}
