/**
 * Guião de narração / leitura enriquecida — Português do Brasil (pt-BR).
 * Fonte única (§8.1): alimenta TTS e painel «Aa». Chave = número do slide (1..26).
 * Localização BR (§8.5): R$, ortografia e léxico do Brasil.
 */
export const NARRATION: Record<number, string> = {
  1: 'Discovery Health é a Discovery especializada em saúde. Aura, a médica virtual, escuta o paciente, estrutura os sintomas, pede auto-exames orientados e prepara um laudo acionável. Ao mesmo tempo, a operação da clínica organiza agenda, cobrança, estoque, nota fiscal e prevenção de fraude. Sete módulos, uma única jornada do paciente.',
  2: 'Antes de começar, o paciente aceita três documentos. Termos de uso, política de privacidade e — o mais sensível — o consentimento de biometria de voz, exigido pela LGPD no artigo 5º, inciso II. O aceite é explícito, documento a documento; nada de letra miúda escondida.',
  3: 'A identificação cruza o CPF com dados públicos da Receita Federal e o endereço com o ViaCEP. Os campos chegam pré-preenchidos, mas o paciente confere e ajusta. Dado público economiza digitação; a conferência mantém o controle com a pessoa.',
  4: 'Antes de liberar qualquer dado, o sistema pergunta: achei alguém com esse CPF, é você? O nome aparece mascarado e só vira texto aberto depois de um gesto explícito do paciente. Confirmação de identidade sem expor dados antes da hora.',
  5: 'Aura se apresenta com voz calorosa, não robótica. Ela explica que vai ouvir com calma, organizar o relato e destacar o que merece atenção médica mais rápida. O texto aparece sincronizado com a fala — o paciente lê e ouve ao mesmo tempo.',
  6: 'Agora o paciente fala livre por até dois minutos, sem perguntas no meio. A forma de onda reage à voz em tempo real. Falar do próprio jeito, sem termo técnico, captura nuance que um formulário perderia.',
  7: 'Aura já escutou. Ela devolve o que entendeu — cefaleia pulsátil há três dias, pior à tarde, sensível à luz — e faz uma pergunta adaptativa, no tom da Comunicação Não-Violenta. Em paralelo, extrai sinais: dor seis de dez, fotossensibilidade, tela como gatilho provável.',
  8: 'Os sinais fisiológicos entram classificados: IMC, pressão arterial, frequência cardíaca, glicemia. Cada valor recebe um rótulo clínico e os red flags acendem. Pressão 128 por 82 vira pré-hipertensão na hora — sem o paciente precisar interpretar número.',
  9: 'A biblioteca de auto-exames traz guias visuais passo a passo: mama, próstata, pele, língua, pulso. O paciente marca o que quer fazer e segue a orientação. No exame de pele, o ABCDE do melanoma guia a captura da lesão.',
  10: 'Trouxe exames? O paciente sobe PDF, JPG ou PNG até vinte megabytes cada. O IconsAI Vision lê cada arquivo em segundo plano — hemograma, colesterol, ressonância — e usa o resultado para montar o laudo. Sem digitação manual.',
  11: 'Com base no áudio, a IA cruza o relato com o catálogo de medicações por busca aumentada por recuperação. Ela sugere o que combina com o que foi contado; o paciente confirma dose e frequência. Dipirona e losartana entram com posologia preenchida.',
  12: 'O chat conduz a entrevista estruturada, citando trechos literais do áudio para mostrar que escutou. As perguntas fecham intensidade, impacto no sono e gatilhos. Cada resposta vira insight no painel lateral.',
  13: 'O laudo sai no formato SOAP — subjetivo, objetivo, avaliação e plano — com token público e selo LGPD-Saúde e ANS. Ao lado, a gestão clínica já se organiza: agenda, estoque com auto-reposição e resumo do paciente em áudio.',
  14: 'A agenda da semana mostra os turnos. Arrastar o paciente para um horário dispara confirmação automática por WhatsApp, com lembrete vinte e quatro horas antes. Sem ligação, sem retrabalho.',
  15: 'O faturamento cruza a curva real com a agenda confirmada, semana a semana. Ticket médio de trezentos e doze reais, cancelamentos em oito vírgula quatro por cento, realizado em noventa e seis por cento do previsto. O gap aparece antes de fechar o mês.',
  16: 'O almoxarifado mostra estoque atual, mínimo e sugestão de compra calculada pelo consumo médio das últimas quatro semanas. Vermelho é abaixo do mínimo. Três itens já estão em pedido pelo auto-restock.',
  17: 'A farmácia controla medicamentos por lote, validade e classe, com rastreabilidade completa para a ANVISA e sincronização com o SNGPC. Os alertas acendem sessenta dias antes do vencimento — dois lotes vencendo em menos de noventa dias.',
  18: 'A cobrança é automatizada por WhatsApp Business com PIX integrado. Sequência humanizada: lembrete três dias antes, um dia antes e no dia. O paciente paga em segundos e o recibo e a nota fiscal saem automáticos.',
  19: 'Um recibo chegou e a IA forense valida. Ela compara metadados, fonte, pixels e cruza com transações reais. Score de confiança trinta e oito de cem: a data foi reescrita sobre o PDF e o valor é quatro vezes a tabela. Reembolso bloqueado, revisão humana em menos de um minuto.',
  20: 'Depois de cada atendimento, a nota fiscal de serviço eletrônica é emitida automaticamente no padrão da prefeitura, com retorno de XML e PDF. Quatorze emitidas hoje, uma aguardando a SEFAZ, webhook ABRASF ao vivo.',
  21: 'A previsão de receita projeta doze meses com um modelo VAR, sazonalidade e feriados. Crescimento anual composto de dezoito vírgula quatro por cento, pico entre março e maio, projeção de três vírgula oito milhões de reais. A banda sombreada é o intervalo de confiança de oitenta por cento.',
  22: 'O diagnóstico assistido vai de sintomas para CID-10 com probabilidade calibrada e daí para um plano de ação. Cefaleia tensional com setenta e dois por cento, enxaqueca com dezenove. A decisão clínica final é sempre do médico; a IA é apoio.',
  23: 'O score de risco populacional combina comorbidades, idade e adesão para apontar quem está em risco de perda. Três pacientes entram em busca ativa hoje. Expectativa de vida ajustada de setenta e oito vírgula quatro anos, intervalo de confiança de noventa e cinco por cento.',
  24: 'A navegação do paciente desenha a trajetória prevista com um modelo de Markov. Cada nó é uma etapa do tratamento; cada aresta, a probabilidade de transição. Caminho conservador, sessenta e sete por cento de recuperação por quatro mil e duzentos reais; intensivo, oitenta e nove por cento por onze mil e oitocentos.',
  25: 'A matriz de evidência cruza combinações de tratamento com desfechos, cada célula com probabilidade e intervalo de confiança de noventa e cinco por cento de fontes médicas. Monoterapia A traz sessenta e dois por cento de remissão; A mais B sobe para setenta e oito; A mais B mais C chega a oitenta e quatro.',
  26: 'Obrigado pela atenção. Discovery Health, uma criação icons ai.',
}
