/**
 * Narration / enriched reading script — American English (en).
 * Single source (§8.1): drives TTS and the «Aa» panel. Key = slide number (1..25).
 * US localization (§8.5): US$, US spelling and conventions.
 */
export const NARRATION: Record<number, string> = {
  1: 'Discovery Health is Discovery specialized for healthcare. Aura, the virtual physician, listens to the patient, structures the symptoms, requests guided self-exams, and prepares an actionable report. In parallel, the clinic operation organizes scheduling, billing, inventory, invoicing, and fraud prevention. Seven modules, one patient journey.',
  2: 'Before starting, the patient accepts three documents. Terms of use, privacy policy, and — the most sensitive — voice biometrics consent, required under HIPAA. The acceptance is explicit, document by document; no hidden fine print.',
  3: 'Identification cross-references the patient against public records and the address against the postal code. Fields arrive prefilled, but the patient reviews and adjusts. Public data saves typing; the review keeps control with the person.',
  4: 'Before releasing any data, the system asks: I found someone matching this record, is this you? The name appears masked and only becomes clear text after an explicit gesture from the patient. Identity confirmation without exposing data too early.',
  5: 'Aura introduces herself in a warm, non-robotic voice. She explains that she will listen calmly, organize the account, and flag what may deserve faster medical attention. The text appears in sync with the speech — the patient reads and hears at the same time.',
  6: 'Now the patient speaks freely for up to two minutes, with no questions in between. The waveform reacts to the voice in real time. Speaking in your own words, without medical jargon, captures nuance a form would miss.',
  7: 'Aura has listened. She reflects back what she understood — pulsating headache for three days, worse in the afternoon, sensitive to light — and asks an adaptive question in a Nonviolent Communication tone. In parallel, she extracts signals: pain six out of ten, photosensitivity, screens as a likely trigger.',
  8: 'Physiological signs come in classified: body mass index, blood pressure, heart rate, blood glucose. Each value gets a clinical label and the red flags light up. Blood pressure 128 over 82 becomes pre-hypertension right away — no number for the patient to interpret.',
  9: 'The self-exam library brings step-by-step visual guides: breast, prostate, skin, tongue, pulse. The patient picks what to do and follows along. For the skin exam, the melanoma ABCDE guides the capture of the lesion.',
  10: 'Brought lab results? The patient uploads PDF, JPG, or PNG up to twenty megabytes each. IconsAI Vision reads each file in the background — blood count, cholesterol, MRI — and uses the result to build the report. No manual typing.',
  11: 'Based on the audio, the AI cross-references the account with the medication catalog using retrieval-augmented generation. It suggests what matches the story; the patient confirms dose and frequency. Medications come in with the dosage prefilled.',
  12: 'The chat runs the structured interview, quoting verbatim snippets from the audio to show it listened. The questions close out intensity, sleep impact, and triggers. Each answer becomes an insight in the side panel.',
  13: 'The report comes out in SOAP format — subjective, objective, assessment, and plan — with a public token and a HIPAA compliance seal. Alongside it, clinical operations are already organized: scheduling, inventory with auto-restock, and an audio summary of the patient.',
  14: 'The weekly schedule shows the shifts. Dragging the patient into a slot triggers automatic confirmation by text message, with a reminder twenty-four hours ahead. No phone call, no rework.',
  15: 'Billing cross-references the actual curve with the confirmed schedule, week by week. Average ticket of fifty-eight dollars, cancellations at eight point four percent, actuals at ninety-six percent of forecast. The gap shows up before the month closes.',
  16: 'The supply room shows current stock, minimum, and a purchase suggestion calculated from the average consumption of the last four weeks. Red is below minimum. Three items are already on order through auto-restock.',
  17: 'The pharmacy controls medications by lot, expiration, and class, with full traceability for the DEA and the FDA. Alerts light up sixty days before expiration — two lots expiring in under ninety days.',
  18: 'Billing is automated through business messaging with integrated card and instant payment. A humanized sequence: a reminder three days out, one day out, and on the day. The patient pays in seconds, and the receipt and invoice go out automatically.',
  19: 'A receipt came in and the forensic AI validates it. It compares metadata, source, and pixels, and cross-references real transactions. Confidence score thirty-eight out of one hundred: the date was rewritten over the PDF and the amount is four times the schedule. Reimbursement blocked, human review in under a minute.',
  20: 'After each visit, the electronic invoice is issued automatically in the local standard, returning XML and PDF. Fourteen issued today, one awaiting the tax authority, the reporting webhook live.',
  21: 'Revenue forecasting projects twelve months with a VAR model, seasonality, and holidays. Compound annual growth of eighteen point four percent, a peak between March and May, a projection of seven hundred and forty thousand dollars. The shaded band is the eighty percent confidence interval.',
  22: 'Assisted diagnosis goes from symptoms to ICD-10 with calibrated probability and on to an action plan. Tension headache at seventy-two percent, migraine at nineteen. The final clinical decision is always the physician’s; the AI is support.',
  23: 'The population risk score combines comorbidities, age, and adherence to flag who is at risk of being lost to follow-up. Three patients enter active outreach today. Adjusted life expectancy of seventy-eight point four years, ninety-five percent confidence interval.',
  24: 'Patient navigation maps the predicted trajectory with a Markov model. Each node is a treatment step; each edge, the transition probability. Conservative path, sixty-seven percent recovery for eight hundred dollars; intensive, eighty-nine percent for twenty-two hundred and fifty.',
  25: 'The evidence matrix crosses treatment combinations with outcomes, each cell carrying a probability and a ninety-five percent confidence interval from medical sources. Monotherapy A yields sixty-two percent remission; A plus B rises to seventy-eight; A plus B plus C reaches eighty-four.',
}
