/**
 * Narration / enriched reading script — Spanish (es).
 * Single source (§8.1): drives TTS and the «Aa» panel. Key = slide number (1..28).
 * Spanish localization (es): clear, neutral clinical Spanish.
 */
export const NARRATION: Record<number, string> = {
  1: 'Discovery Health es Discovery especializado en atención sanitaria. Aura, el médico virtual, escucha al paciente, estructura los síntomas, solicita autoexámenes guiados y prepara un informe procesable. Paralelamente, la operación de la clínica organiza la programación, facturación, inventario, facturación y prevención de fraude. Siete módulos, un viaje de paciente.',
  2: 'Antes de empezar, el paciente acepta tres documentos. Términos de uso, política de privacidad y, lo más sensible, consentimiento biométrico de voz, requerido según HIPAA. La aceptación es explícita, documento por documento; sin letra pequeña oculta.',
  3: 'La identificación compara al paciente con los registros públicos y la dirección con el código postal. Los campos llegan prellenados, pero el paciente los revisa y ajusta. Los datos públicos ahorran escribir; la revisión mantiene el control con la persona.',
  4: 'Antes de publicar cualquier dato, el sistema pregunta: Encontré a alguien que coincide con este registro, ¿eres tú? El nombre aparece enmascarado y sólo se vuelve claro tras un gesto explícito del paciente. Confirmación de identidad sin exponer datos demasiado pronto.',
  5: 'Aura se presenta con una voz cálida y no robótica. Ella explica que escuchará con calma, organizará la cuenta y señalará lo que pueda merecer una atención médica más rápida. El texto aparece sincronizado con el habla: el paciente lee y escucha al mismo tiempo.',
  6: 'Ahora el paciente habla libremente durante un máximo de dos minutos, sin preguntas de por medio. La forma de onda reacciona a la voz en tiempo real. Hablar con sus propias palabras, sin jerga médica, capta matices que un formulario pasaría por alto.',
  7: 'Aura ha escuchado. Ella reflexiona sobre lo que entendió (dolor de cabeza pulsante durante tres días, peor por la tarde, sensible a la luz) y hace una pregunta adaptativa en un tono de comunicación no violenta. Paralelamente, extrae señales: dolor seis sobre diez, fotosensibilidad, pantallas como probable desencadenante.',
  8: 'Los signos fisiológicos se clasifican: índice de masa corporal, presión arterial, frecuencia cardíaca, glucosa en sangre. Cada valor recibe una etiqueta clínica y se encienden las banderas rojas. La presión arterial 128 sobre 82 se convierte inmediatamente en prehipertensión: no hay un número que el paciente pueda interpretar.',
  9: 'La biblioteca de autoexámenes trae guías visuales paso a paso: mama, próstata, piel, lengua, pulso. El paciente elige qué hacer y lo sigue. Para el examen de la piel, el melanoma ABCDE guía la captura de la lesión.',
  10: '¿Trajo resultados de laboratorio? El paciente carga PDF, JPG o PNG de hasta veinte megabytes cada uno. IconsAI Vision lee cada archivo en segundo plano (conteo sanguíneo, colesterol, resonancia magnética) y utiliza el resultado para crear el informe. Sin escritura manual.',
  11: 'Según el audio, la IA cruza la cuenta con el catálogo de medicamentos mediante generación de recuperación aumentada. Sugiere lo que coincide con la historia; el paciente confirma dosis y frecuencia. Los medicamentos llegan con la dosis precargada.',
  12: 'El chat ejecuta la entrevista estructurada, citando fragmentos textuales del audio para demostrar que fue escuchado. Las preguntas cierran la intensidad, el impacto del sueño y los desencadenantes. Cada respuesta se convierte en una idea en el panel lateral.',
  13: 'El informe se publica en formato SOAP (subjetivo, objetivo, evaluación y plan) con un token público y un sello de cumplimiento de HIPAA. Junto a él, ya están organizadas las operaciones clínicas: programación, inventario con reabastecimiento automático y resumen en audio del paciente.',
  14: 'Una vez completado el recorrido del paciente, DiscoveryHealth se hace cargo de las operaciones de la clínica. Desde aquí el médico ve la gestión de recursos: programación inteligente, previsión de ingresos, inventario, farmacia, cobro de pagos, antifraude de recibos, facturación automática y proyección de ingresos. Todos conectados al mismo paciente.',
  15: 'El horario semanal muestra los turnos. Al arrastrar al paciente a una ranura se activa una confirmación automática mediante mensaje de texto, con un recordatorio con veinticuatro horas de antelación. Sin llamadas telefónicas, sin retrabajos.',
  16: 'La facturación cruza la curva real con el cronograma confirmado, semana a semana. Boleto promedio de cincuenta y ocho dólares, cancelaciones al ocho coma cuatro por ciento, reales al noventa y seis por ciento de lo previsto. La brecha aparece antes de que cierre el mes.',
  17: 'La sala de suministros muestra el stock actual, mínimo y una sugerencia de compra calculada a partir del consumo medio de las últimas cuatro semanas. El rojo está por debajo del mínimo. Ya hay pedidos de tres artículos mediante reabastecimiento automático.',
  18: 'La farmacia controla los medicamentos por lote, vencimiento y clase, con total trazabilidad para la DEA y la FDA. Las alertas se encienden sesenta días antes del vencimiento: dos lotes vencen en menos de noventa días.',
  19: 'La facturación se automatiza a través de mensajería empresarial con tarjeta integrada y pago instantáneo. Una secuencia humanizada: un recordatorio a tres días, a un día y al día. El paciente paga en segundos y el recibo y la factura salen automáticamente.',
  20: 'Llegó un recibo y la IA forense lo valida. Compara metadatos, fuentes y píxeles, y hace referencias cruzadas de transacciones reales. Puntuación de confianza treinta y ocho sobre cien: la fecha se reescribió en el PDF y el importe es cuatro veces mayor que el previsto. Reembolso bloqueado, revisión humana en menos de un minuto.',
  21: 'Después de cada visita, la factura electrónica se emite automáticamente en el estándar local, devolviendo XML y PDF. Catorce emitidos hoy, uno a la espera de la autoridad fiscal, el webhook de informes en vivo.',
  22: 'Proyectos de previsión de ingresos a doce meses con modelo VAR, estacionalidad y festivos. Crecimiento anual compuesto de dieciocho coma cuatro por ciento, un pico entre marzo y mayo, una proyección de setecientos cuarenta mil dólares. La banda sombreada es el intervalo de confianza del ochenta por ciento.',
  23: 'Ahora entramos en el panel de control, la capa de inteligencia clínica. Diagnóstico asistido ICD-10, esperanza de vida, navegación del paciente y combinaciones de tratamientos. Esto es apoyo a la toma de decisiones; La última palabra siempre la tiene el médico.',
  24: 'El diagnóstico asistido pasa de los síntomas a la CIE-10 con probabilidad calibrada y luego a un plan de acción. Dolor de cabeza tensional al setenta y dos por ciento, migraña al diecinueve. La decisión clínica final es siempre del médico; la IA es apoyo.',
  25: 'La puntuación de riesgo de la población combina comorbilidades, edad y adherencia para señalar quién está en riesgo de perderse durante el seguimiento. Tres pacientes ingresan hoy a actividades de extensión activa. Esperanza de vida ajustada de setenta y ocho coma cuatro años, intervalo de confianza del noventa y cinco por ciento.',
  26: 'La navegación del paciente mapea la trayectoria prevista con un modelo de Markov. Cada nodo es un paso de tratamiento; cada borde, la probabilidad de transición. Camino conservador, recuperación del sesenta y siete por ciento por ochocientos dólares; intensivo, el ochenta y nueve por ciento para dos mil doscientos cincuenta.',
  27: 'La matriz de evidencia cruza combinaciones de tratamientos con resultados, cada celda tiene una probabilidad y un intervalo de confianza del noventa y cinco por ciento de fuentes médicas. La monoterapia A produce una remisión del sesenta y dos por ciento; A más B ascienden a setenta y ocho; A más B más C llega a ochenta y cuatro.',
  28: 'Gracias por tu tiempo. Discovery Health, por iconos ai.',
}
